const fs = require('fs');

const part1 = [
  "import React, { useState, useMemo } from 'react';",
  "import { DatasetBundle, DerivedMineMetrics, RuleDerivedAlert } from '../../types/minegov';",
  "import { DemoSourceBadge } from '../common/DemoSourceBadge';",
  "import { exportReportToCSV, triggerPrintReport } from '../../services/reportGenerator';",
  "import { FileSpreadsheet, Printer, Download, FileText, CheckCircle2 } from 'lucide-react';",
  "",
  "interface ReportsViewProps {",
  "  data: DatasetBundle;",
  "  metrics: DerivedMineMetrics[];",
  "  alerts: RuleDerivedAlert[];",
  "  selectedMineId: string;",
  "}",
  "",
  "const REPORT_TYPES = [",
  "  { id: 'EXECUTIVE_SUMMARY', title: 'Executive Mine Governance & Risk Summary', desc: 'Overall risk score breakdown, compliance index, and top 5 risk drivers across all mines.' },",
  "  { id: 'DGMS_STATUTORY', title: 'DGMS Statutory Compliance & Inspection Report', desc: 'Detailed compliance status for DGMS Act/CMR rules, pending licenses, and checklist scores.' },",
  "  { id: 'MOEFCC_ENV', title: 'MoEFCC Environmental Monitoring Audit', desc: 'Air quality (PM2.5, PM10), water pH discharge, and noise limit exceedances log.' },",
  "  { id: 'CAPA_AGING', title: 'CAPA Aging & Overdue Action Items Board', desc: 'Kanban audit of open, overdue, and pending verification corrective actions.' },",
  "  { id: 'SAFETY_INCIDENT', title: 'Safety Incidents & Telemetry Anomaly Summary', desc: 'Historical accident classification, root causes, and IoT sensor anomaly events.' },",
  "  { id: 'CONTRACTOR_PERF', title: 'Contractor Risk Tier & Worker Fitness Audit', desc: 'Outsourced contractor safety audit scores and worker vocational/medical status.' },",
  "  { id: 'FLEET_HEALTH', title: 'Heavy Equipment Maintenance & Breakdown Summary', desc: 'Machinery health scores, 24-hour breakdown hours, and operational status.' },",
  "  { id: 'DOCUMENT_OCR', title: 'Statutory Clearance Ingestion & OCR Audit', desc: 'Document verification queue, OCR confidence scores, and upcoming expiry dates.' }",
  "];",
  "",
].join('\n');

const part2 = [
  "/* Helpers */",
  "const KPI: React.FC<{ label: string; value: number | string; color?: string }> = ({ label, value, color }) => (",
  "  <div className=\"text-center p-3 bg-carbon-850 rounded-lg border border-carbon-700\">",
  "    <div className={`text-2xl font-bold ${color || 'text-white'}`}>{value}</div>",
  "    <div className=\"text-[10px] text-warm-slate\">{label}</div>",
  "  </div>",
  ");",
  "const rc = (b: string) => b === 'Critical' ? 'bg-rose-500/20 text-rose-400' : b === 'High' ? 'bg-amber-500/20 text-amber-400' : b === 'Moderate' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-emerald-500/20 text-emerald-400';",
  "const Row: React.FC<{ children: React.ReactNode }> = ({ children }) => <div className=\"p-2 bg-carbon-850 rounded-lg border border-carbon-700 flex justify-between items-center\">{children}</div>;",
  "const Sec: React.FC<{ children: React.ReactNode }> = ({ children }) => <div className=\"font-bold text-copper-light uppercase border-b border-carbon-800 pb-1 text-sm\">{children}</div>;",
  "const Lst: React.FC<{ children: React.ReactNode }> = ({ children }) => <div className=\"font-bold text-warm-pale border-b border-carbon-800 pb-1\">{children}</div>;",
  "",
  "/* Executive Summary */",
  "const ExecutiveReport: React.FC<{ metrics: DerivedMineMetrics[]; alerts: RuleDerivedAlert[] }> = ({ metrics, alerts }) => (",
  "  <>",
  "    <Sec>Executive Mine Governance and Risk Summary</Sec>",
  "    <div className=\"grid grid-cols-3 gap-3 mb-3\">",
  "      <KPI label=\"Total Mines\" value={metrics.length} />",
  "      <KPI label=\"High/Critical Risk\" value={metrics.filter(m => m.risk_band === 'Critical' || m.risk_band === 'High').length} color=\"text-rose-400\" />",
  "      <KPI label=\"Critical Alerts\" value={alerts.filter(a => a.severity === 'CRITICAL').length} color=\"text-amber-400\" />",
  "    </div>",
  "    <Lst>Mine Risk Breakdown</Lst>",
  "    {metrics.length === 0 && <div className=\"text-warm-slate italic\">No mine metrics loaded. Upload CSV data first.</div>}",
  "    {metrics.map(m => (",
  "      <div key={m.mine_id} className=\"p-3 bg-carbon-850 rounded-lg border border-carbon-700 space-y-1\">",
  "        <div className=\"flex justify-between font-bold text-warm-pale\">",
  "          <span>{m.mine_name || m.mine_id}</span>",
  "          <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${rc(m.risk_band)}`}>{m.risk_band} ({m.overall_risk})</span>",
  "        </div>",
  "        <div className=\"grid grid-cols-5 gap-2 text-[10px] text-warm-slate\">",
  "          <span>Compliance: <span className=\"text-warm-sand\">{(100 - m.compliance_risk).toFixed(0)}%</span></span>",
  "          <span>Safety: <span className=\"text-warm-sand\">{m.safety_risk}</span></span>",
  "          <span>Env: <span className=\"text-warm-sand\">{m.environment_risk}</span></span>",
  "          <span>Equip: <span className=\"text-warm-sand\">{m.equipment_risk}</span></span>",
  "          <span>Ops: <span className=\"text-warm-sand\">{m.operations_risk}</span></span>",
  "        </div>",
  "      </div>",
  "    ))}",
  "  </>",
  ");",
  "",
].join('\n');

fs.writeFileSync('D:/smart-mine/src/components/views/ReportsView.tsx', part1 + part2);
console.log('written', (part1 + part2).length);