// ────────────────────────────────────────────────────────────────
// Reports & Export — complaints grouped by category, PDF export
// ────────────────────────────────────────────────────────────────
import React, { useEffect, useState, useMemo } from 'react';
import {
  FileText, Download, Filter, ChevronDown, ChevronRight, BarChart3,
  AlertTriangle, CheckCircle2, Clock, XCircle, Calendar,
} from 'lucide-react';
import { complaintsService } from '../lib/complaints';
import { COMPLAINT_CATEGORIES, Complaint } from '../lib/types';
import { computeStats, formatDate, SEVERITY_COLORS } from '../lib/analytics';
import { Card, Spinner, SeverityBadge, StatusBadge, Button, EmptyState } from './ui/primitives';
import { Select, TextInput } from './ui/inputs';
import { downloadPdfBlob, generateComplaintsReportPdf } from '../lib/complaintReportPdf';

// ── PDF export ────────────────────────────────────────────────
// Complaint PDFs are generated by ../lib/complaintReportPdf.ts.

// ── Category Report Card ──────────────────────────────────────
const CategoryReportCard: React.FC<{
  category: string;
  complaints: Complaint[];
  expanded: boolean;
  onToggle: () => void;
  onExportCategory: (cat: string, complaints: Complaint[]) => void;
}> = ({ category, complaints, expanded, onToggle, onExportCategory }) => {
  const total = complaints.length;
  const open = complaints.filter((c) => ['Submitted', 'Under Review', 'Assigned', 'Inspection Required', 'Action In Progress', 'Escalated'].includes(c.status)).length;
  const resolved = complaints.filter((c) => c.status === 'Verified').length;
  const critical = complaints.filter((c) => c.severity === 'Critical').length;
  const high = complaints.filter((c) => c.severity === 'High').length;

  const severityBreakdown = ['Critical', 'High', 'Medium', 'Low'].map((s) => ({
    label: s,
    count: complaints.filter((c) => c.severity === s).length,
    color: SEVERITY_COLORS[s as keyof typeof SEVERITY_COLORS],
  }));

  return (
    <Card className="overflow-hidden">
      <button onClick={onToggle} className="w-full flex items-center gap-3 px-4 py-3 hover:bg-carbon-700/30 transition-colors text-left">
        {expanded ? <ChevronDown className="w-4 h-4 text-copper-light shrink-0" /> : <ChevronRight className="w-4 h-4 text-warm-slate shrink-0" />}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-sm font-bold text-warm-pale">{category}</span>
            <span className="text-[10px] font-mono text-warm-slate bg-carbon-850 px-1.5 py-0.5 rounded">{total} complaint{total !== 1 ? 's' : ''}</span>
          </div>
          <div className="flex items-center gap-3 mt-1 text-[11px] text-warm-slate">
            <span className="flex items-center gap-1"><Clock className="w-3 h-3 text-amber-400" /> {open} open</span>
            <span className="flex items-center gap-1"><CheckCircle2 className="w-3 h-3 text-emerald-400" /> {resolved} verified</span>
            {critical > 0 && <span className="flex items-center gap-1 text-rose-400"><AlertTriangle className="w-3 h-3" /> {critical} critical</span>}
            {high > 0 && <span className="flex items-center gap-1 text-orange-400"><AlertTriangle className="w-3 h-3" /> {high} high</span>}
          </div>
        </div>
        <Button variant="ghost" onClick={(e) => { e.stopPropagation(); onExportCategory(category, complaints); }} className="text-xs shrink-0" title={`Export ${category} complaints as PDF`}>
          <Download className="w-3.5 h-3.5" /> PDF
        </Button>
      </button>

      {expanded && (
        <div className="border-t border-carbon-700/60">
          {/* Severity bar */}
          <div className="px-4 py-3 border-b border-carbon-700/30">
            <div className="text-[10px] font-mono uppercase tracking-wider text-warm-slate/60 mb-2">Severity Breakdown</div>
            <div className="flex gap-1 h-3 rounded-full overflow-hidden bg-carbon-850">
              {severityBreakdown.map((s) =>
                s.count > 0 ? (
                  <div key={s.label} className={`${s.color.split(' ')[1]} transition-all`} style={{ width: `${(s.count / total) * 100}%` }} title={`${s.label}: ${s.count}`} />
                ) : null,
              )}
            </div>
            <div className="flex gap-3 mt-1.5">
              {severityBreakdown.map((s) => (
                <span key={s.label} className={`text-[10px] font-mono ${s.color.split(' ')[0]}`}>{s.label}: {s.count}</span>
              ))}
            </div>
          </div>
          {/* Complaints table */}
          <div className="overflow-x-auto max-h-80 overflow-y-auto">
            <table className="w-full text-xs">
              <thead className="sticky top-0 bg-carbon-800">
                <tr className="text-warm-slate border-b border-carbon-700/60">
                  <th className="text-left px-4 py-2 font-mono text-[10px] uppercase">ID</th>
                  <th className="text-left px-4 py-2 text-[10px] uppercase">Title</th>
                  <th className="text-center px-4 py-2 text-[10px] uppercase">Severity</th>
                  <th className="text-center px-4 py-2 text-[10px] uppercase">Status</th>
                  <th className="text-left px-4 py-2 text-[10px] uppercase">Reported By</th>
                  <th className="text-right px-4 py-2 text-[10px] uppercase">Reported</th>
                  <th className="text-right px-4 py-2 text-[10px] uppercase">Created</th>
                  <th className="text-right px-4 py-2 text-[10px] uppercase">Last Updated</th>
                </tr>
              </thead>
              <tbody>
                {complaints.map((c) => (
                  <tr key={c.id} className="border-b border-carbon-700/30 hover:bg-carbon-850/60">
                    <td className="px-4 py-2 font-mono text-copper-light font-bold whitespace-nowrap">{c.complaint_number}</td>
                    <td className="px-4 py-2 text-warm-pale max-w-[220px] truncate">{c.title}</td>
                    <td className="px-4 py-2 text-center"><SeverityBadge value={c.severity} /></td>
                    <td className="px-4 py-2 text-center"><StatusBadge value={c.status} /></td>
                    <td className="px-4 py-2 text-warm-slate">{c.reported_by_name || '—'}</td>
                    <td className="px-4 py-2 text-right text-warm-slate whitespace-nowrap">{formatDate(c.reported_at)}</td>
                    <td className="px-4 py-2 text-right text-warm-slate/70 whitespace-nowrap">{formatDate(c.created_at)}</td>
                    <td className="px-4 py-2 text-right text-warm-slate/70 whitespace-nowrap">{formatDate(c.updated_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </Card>
  );
};

// ── Main ReportsView ──────────────────────────────────────────
export const ReportsView: React.FC = () => {
  const [complaints, setComplaints] = useState<Complaint[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());
  const [categoryFilter, setCategoryFilter] = useState('All');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [search, setSearch] = useState('');

  useEffect(() => {
    const load = async () => {
      setLoading(true);
      try {
        const list = await complaintsService.list();
        setComplaints(list);
      } catch (err) {
        console.error('Failed to load complaints for reports:', err);
      }
      setLoading(false);
    };
    load();
  }, []);

  const filtered = useMemo(() => {
    let out = complaints;
    if (categoryFilter !== 'All') out = out.filter((c) => c.category === categoryFilter);
    if (dateFrom) out = out.filter((c) => c.reported_at >= dateFrom);
    if (dateTo) {
      const toDate = new Date(dateTo);
      toDate.setHours(23, 59, 59, 999);
      out = out.filter((c) => new Date(c.reported_at) <= toDate);
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      out = out.filter((c) =>
        c.complaint_number.toLowerCase().includes(q) ||
        c.title.toLowerCase().includes(q) ||
        c.reported_by_name?.toLowerCase().includes(q) ||
        c.category.toLowerCase().includes(q)
      );
    }
    return out;
  }, [complaints, categoryFilter, dateFrom, dateTo, search]);

  const stats = useMemo(() => computeStats(filtered), [filtered]);

  const complaintsByCategory = useMemo(() => {
    const grouped: Record<string, Complaint[]> = {};
    for (const cat of COMPLAINT_CATEGORIES) {
      grouped[cat] = filtered.filter((c) => c.category === cat);
    }
    const knownSet = new Set(COMPLAINT_CATEGORIES);
    const unknown = filtered.filter((c) => !knownSet.has(c.category as any));
    if (unknown.length > 0) grouped['Other'] = [...(grouped['Other'] ?? []), ...unknown];
    return grouped;
  }, [filtered]);

  const activeCategories = useMemo(
    () => Object.entries(complaintsByCategory).filter(([, list]) => list.length > 0).sort((a, b) => b[1].length - a[1].length),
    [complaintsByCategory],
  );

  const toggleCategory = (cat: string) => {
    setExpandedCategories((prev) => {
      const next = new Set(prev);
      if (next.has(cat)) next.delete(cat); else next.add(cat);
      return next;
    });
  };

  const expandAll = () => setExpandedCategories(new Set(activeCategories.map(([c]) => c)));
  const collapseAll = () => setExpandedCategories(new Set());

  const exportAllPDF = () => {
    if (!filtered.length) return;
    const dateStr = new Date().toISOString().slice(0, 10);
    const blob = generateComplaintsReportPdf(
      {
        orgName: 'Coal Mine Compliance System',
        mineName: complaints.find((c) => c.mine_name)?.mine_name ?? null,
        reportTitle: categoryFilter && categoryFilter !== 'All' ? `Complaints Report - ${categoryFilter}` : 'Complaints Report',
        category: categoryFilter,
        filtersNote: `${filtered.length} complaint${filtered.length !== 1 ? 's' : ''}`,
      },
      filtered,
    );
    downloadPdfBlob(blob, `complaints_report_${dateStr}.pdf`);
  };

  const exportCategoryPDF = (category: string, categoryComplaints: Complaint[]) => {
    if (!categoryComplaints.length) return;
    const dateStr = new Date().toISOString().slice(0, 10);
    const blob = generateComplaintsReportPdf(
      {
        orgName: 'Coal Mine Compliance System',
        mineName: complaints.find((c) => c.mine_name)?.mine_name ?? null,
        reportTitle: `${category} Complaints Report`,
        category,
        filtersNote: `${categoryComplaints.length} complaint${categoryComplaints.length !== 1 ? 's' : ''}`,
      },
      categoryComplaints,
    );
    downloadPdfBlob(blob, `${category.toLowerCase().replace(/\s+/g, '_')}_complaints_${dateStr}.pdf`);
  };

  if (loading) return <Spinner size="lg" label="Loading report data..." />;

  const categoryOptions = [
    { value: 'All', label: 'All Categories' },
    ...COMPLAINT_CATEGORIES.map((c) => ({ value: c, label: c })),
  ];

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-copper-light" />
          <div>
            <h1 className="text-lg font-extrabold text-warm-pale">Reports & Export</h1>
            <p className="text-xs text-warm-slate">Complaint reports organized by category · {filtered.length} of {complaints.length} total</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" onClick={expandAll} className="text-xs">Expand All</Button>
          <Button variant="ghost" onClick={collapseAll} className="text-xs">Collapse All</Button>
          <Button onClick={exportAllPDF} className="text-xs">
            <Download className="w-4 h-4" /> Export All (PDF)
          </Button>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Card>
          <div className="text-center">
            <p className="text-2xl font-extrabold text-warm-pale">{stats.total}</p>
            <p className="text-[10px] font-mono uppercase text-warm-slate tracking-wider mt-0.5">Total Complaints</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-2xl font-extrabold text-amber-400">{stats.open}</p>
            <p className="text-[10px] font-mono uppercase text-warm-slate tracking-wider mt-0.5">Open / Pending</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-2xl font-extrabold text-emerald-400">{stats.resolved}</p>
            <p className="text-[10px] font-mono uppercase text-warm-slate tracking-wider mt-0.5">Verified / Closed</p>
          </div>
        </Card>
        <Card>
          <div className="text-center">
            <p className="text-2xl font-extrabold text-rose-400">{stats.critical}</p>
            <p className="text-[10px] font-mono uppercase text-warm-slate tracking-wider mt-0.5">Critical</p>
          </div>
        </Card>
      </div>

      {/* Compliance & Resolution Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <Card>
          <div className="flex items-center gap-3">
            <BarChart3 className="w-5 h-5 text-copper-light" />
            <div>
              <p className="text-lg font-extrabold text-warm-pale">{stats.compliancePct}%</p>
              <p className="text-[10px] font-mono text-warm-slate">Compliance Rate</p>
            </div>
          </div>
          <div className="mt-2 h-2 bg-carbon-850 rounded-full overflow-hidden">
            <div className="h-full bg-emerald-500 rounded-full transition-all" style={{ width: `${stats.compliancePct}%` }} />
          </div>
        </Card>
        <Card>
          <div className="flex items-center gap-3">
            <Clock className="w-5 h-5 text-copper-light" />
            <div>
              <p className="text-lg font-extrabold text-warm-pale">{stats.avgResolutionHours}h</p>
              <p className="text-[10px] font-mono text-warm-slate">Avg. Resolution Time</p>
            </div>
          </div>
        </Card>
        <Card>
          <div className="flex items-center gap-3">
            <XCircle className="w-5 h-5 text-rose-400" />
            <div>
              <p className="text-lg font-extrabold text-warm-pale">{stats.overdue}</p>
              <p className="text-[10px] font-mono text-warm-slate">Overdue Complaints</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <div className="flex items-center gap-2 flex-wrap">
          <Filter className="w-4 h-4 text-warm-slate shrink-0" />
          <div className="flex items-center gap-2 bg-carbon-850 px-3 py-1.5 rounded-lg border border-carbon-700/60 flex-1 min-w-[180px] max-w-xs">
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search complaints..." className="bg-transparent text-xs text-warm-pale outline-none w-full placeholder-warm-slate/60" />
          </div>
          <Select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} options={categoryOptions} className="w-44" />
          <div className="flex items-center gap-1.5">
            <Calendar className="w-3.5 h-3.5 text-warm-slate" />
            <TextInput type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="w-36" />
            <span className="text-warm-slate text-xs">to</span>
            <TextInput type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="w-36" />
          </div>
          {(categoryFilter !== 'All' || dateFrom || dateTo || search) && (
            <Button variant="ghost" onClick={() => { setCategoryFilter('All'); setDateFrom(''); setDateTo(''); setSearch(''); }} className="text-xs text-warm-slate">
              <XCircle className="w-3.5 h-3.5" /> Clear
            </Button>
          )}
        </div>
      </Card>

      {/* Category Status Overview Table */}
      {activeCategories.length > 0 && (
        <Card title="Category Status Overview" subtitle="Complaints per category and status">
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-warm-slate border-b border-carbon-700/60">
                  <th className="text-left px-3 py-2 font-mono text-[10px] uppercase">Category</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Total</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Open</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Resolved</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Verified</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Escalated</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">Critical</th>
                  <th className="text-center px-3 py-2 text-[10px] uppercase">High</th>
                </tr>
              </thead>
              <tbody>
                {activeCategories.map(([cat, list]) => {
                  const OPEN = ['Submitted', 'Under Review', 'Assigned', 'Inspection Required', 'Action In Progress'];
                  const openCount = list.filter((c) => OPEN.includes(c.status)).length;
                  const resolvedCount = list.filter((c) => c.status === 'Resolved').length;
                  const verifiedCount = list.filter((c) => c.status === 'Verified').length;
                  const escalatedCount = list.filter((c) => c.status === 'Escalated').length;
                  const criticalCount = list.filter((c) => c.severity === 'Critical').length;
                  const highCount = list.filter((c) => c.severity === 'High').length;
                  return (
                    <tr key={cat} className="border-b border-carbon-700/30 hover:bg-carbon-850/40">
                      <td className="px-3 py-2 font-semibold text-warm-pale">{cat}</td>
                      <td className="px-3 py-2 text-center font-mono font-bold text-warm-pale">{list.length}</td>
                      <td className="px-3 py-2 text-center font-mono text-amber-400">{openCount}</td>
                      <td className="px-3 py-2 text-center font-mono text-teal-400">{resolvedCount}</td>
                      <td className="px-3 py-2 text-center font-mono text-emerald-400">{verifiedCount}</td>
                      <td className="px-3 py-2 text-center font-mono text-red-400">{escalatedCount}</td>
                      <td className="px-3 py-2 text-center font-mono text-rose-400">{criticalCount}</td>
                      <td className="px-3 py-2 text-center font-mono text-orange-400">{highCount}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      {/* Complaint Reports by Category */}
      <div className="space-y-2">
        <h2 className="text-sm font-bold text-warm-pale">
          Complaint Reports by Category ({activeCategories.length} categories with data)
        </h2>
        {activeCategories.length === 0 ? (
          <EmptyState title="No complaints found" subtitle="Adjust your filters or submit a new complaint via Report Issue." />
        ) : (
          activeCategories.map(([cat, list]) => (
            <CategoryReportCard
              key={cat}
              category={cat}
              complaints={list}
              expanded={expandedCategories.has(cat)}
              onToggle={() => toggleCategory(cat)}
              onExportCategory={exportCategoryPDF}
            />
          ))
        )}
      </div>
    </div>
  );
};


